#!/usr/bin/env bash

function _launch_config_profile {
  local shome="${_launch_config_home:-"$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"}"
  PATH="$shome/bin:$PATH"
}

_launch_config_profile
